project:
  type: website
  output-dir: docs

website:
  title: "MY WORKSPACE"
  # site-url: https://ds21.io
  description: "A great sample blog"

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: resume
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css




# website:
#   title: "MyBlog"
#   site-url: https://ds21.io
#   description: "A great sample blog"
  
#   navbar:
#     right:
#       - about.qmd
#       - icon: github
#         href: https://github.com/dsaha21
#       - icon: twitter
#         href: https://twitter.com
# format:
#   html:
#     theme: cosmo
#     css: styles.css -->




